export const PAYPAL_WEBHOOK_EVENTS = {
  SUBSCRIPTION_ACTIVATED: "BILLING.SUBSCRIPTION.ACTIVATED",
  SUBSCRIPTION_CANCELLED: "BILLING.SUBSCRIPTION.CANCELLED",
  SUBSCRIPTION_EXPIRED: "BILLING.SUBSCRIPTION.EXPIRED",
  SUBSCRIPTION_PAYMENT_FAILED: "BILLING.SUBSCRIPTION.PAYMENT.FAILED",
} as const;
